# Generated by Django 4.2.5 on 2023-10-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
    ]
