# Generated by Django 4.2.5 on 2023-10-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='team',
        ),
    ]
