# Generated by Django 4.2.5 on 2023-10-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_comment_created_by'),
        ('product', '0003_advertisement_activity'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaigns',
            new_name='Campaign',
        ),
    ]
