# Generated by Django 4.2.5 on 2023-10-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='ads',
        ),
    ]
