# Generated by Django 4.2.5 on 2023-10-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaign_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='clients',
        ),
    ]
