# Generated by Django 4.2.5 on 2023-10-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaignclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignClient',
        ),
    ]
