# Generated by Django 4.1.7 on 2023-09-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_active_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='active_team_id',
            new_name='active_team',
        ),
    ]
