# Generated by Django 4.1.7 on 2023-09-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='created_by',
        ),
    ]
