# Generated by Django 4.1.7 on 2023-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_advertisement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
