# Generated by Django 4.2.5 on 2023-10-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaign_ads'),
        ('product', '0003_advertisement_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='campaigns.campaign'),
        ),
    ]
